version: '3'
services:
  angular:
    build: frontend/
    depends_on:
      - spring-boot
    ports:
      - "4200:4200"
    volumes:
      - "./frontend/:/var/www"
      - "/var/www/node_modules"
  spring-boot:
    build: backend/
    # depends on database is reduntant because of links
    depends_on:
      - database
      - mailserver
    ports:
      - "8080:8080"
    volumes:
      - "./backend/target/:/var/www/"
  database:
    image: mdillon/postgis
    environment:
      POSTGRES_PASSWORD: "aipolito"
    expose:
      - "5432"
  mailserver:
    image: digiplant/fake-smtp
    ports:
      - "1025:25"
    volumes:
      - ./email:/var/mail
    

    
